version: "3.8"

services:

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - 2181:2181
    container_name: zookeeper

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - 9092:9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPIC: "mans_topic:1:3"

  agent:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile_agent
    depends_on:
     - kafka
    ports:
      - "8081:8081"
  server:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile_server
    depends_on:
      - kafka
    ports:
      - "8080:8080"
