# don't commit your local changes ;)
spring:
  datasource:
    url: jdbc:mysql://mysql.agh.edu.pl:3306/jakubmaz?useSSL=false
    username: jakubmaz
    password: CnwX37JtXTbQCSSe
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MariaDB102Dialect
    hibernate.ddl-auto: create-drop
    show-sql: true

server:
  error:
    include-message: always