FROM maven:3.8.3-openjdk-17 as builder

WORKDIR /workdir

COPY server .

RUN mvn package -DskipTests

FROM openjdk:17.0-jdk-slim

WORKDIR /

COPY --from=builder /workdir/target/server-*.jar /server.jar

CMD ["java", "-jar", "/server.jar"]
