FROM maven:3.8.3-openjdk-17 as builder

WORKDIR /workdir

COPY agent/ agent/

RUN cd /workdir/agent && mvn package -DskipTests

FROM openjdk:17.0-jdk-slim

WORKDIR /

COPY --from=builder /workdir/agent/target/agent-*.jar /agent.jar

COPY --from=builder /workdir/agent/src/main/java/com/zstwp/mans/alerts/logs.txt /agent/src/main/java/com/zstwp/mans/alerts/logs.txt

CMD ["java", "-jar", "/agent.jar"]
