FROM maven:3.8.3-openjdk-17 as builder

WORKDIR /workdir

COPY agent .

RUN mvn package -DskipTests

FROM openjdk:17.0-jdk-slim

WORKDIR /

COPY --from=builder /workdir/target/agent-*.jar /agent.jar

CMD ["java", "-jar", "/agent.jar"]
